#!/usr/bin/env python3
"""
Demonstration of improved tempo tracking capabilities in aubio-ledfx.

This example compares:
1. Original mode: Default tempo tracking
2. Optimized mode: Using tempo priors and adaptive window sizing

Uses the test audio files generated by generate_tempo_test_audio.py
"""

import sys
import os
import numpy as np
from aubio import source, tempo
import json
import time

def load_ground_truth(json_file):
    """Load ground truth data from JSON file."""
    with open(json_file, 'r') as f:
        return json.load(f)

def detect_tempo_original(audio_file, samplerate=0):
    """
    Original mode: Default tempo tracking without optimizations.
    
    Returns: list of (time, bpm, confidence) tuples
    """
    win_s = 1024
    hop_s = 256
    
    s = source(audio_file, samplerate, hop_s)
    samplerate = s.samplerate
    t = tempo("default", win_s, hop_s, samplerate)
    
    detections = []
    total_frames = 0
    
    while True:
        samples, read = s()
        is_beat = t(samples)
        
        # Record tempo at each beat
        if is_beat:
            current_time = total_frames / float(samplerate)
            bpm = t.get_bpm()
            confidence = t.get_confidence()
            detections.append((current_time, bpm, confidence))
        
        total_frames += read
        if read < hop_s:
            break
    
    return detections, samplerate

def detect_tempo_optimized(audio_file, expected_tempo=120, samplerate=0):
    """
    Optimized mode: Using tempo priors and adaptive window sizing.
    
    Args:
        audio_file: Path to audio file
        expected_tempo: Expected tempo in BPM (for prior)
        samplerate: Sample rate (0 = auto-detect)
    
    Returns: list of (time, bpm, confidence) tuples
    """
    win_s = 1024
    hop_s = 256
    
    s = source(audio_file, samplerate, hop_s)
    samplerate = s.samplerate
    t = tempo("default", win_s, hop_s, samplerate)
    
    # Apply tempo prior - center detection around expected tempo
    # For test file with varying tempos, use a wide prior
    t.set_tempo_prior_mean(expected_tempo)
    t.set_tempo_prior_std(2.5)  # Allow ±2.5 BPM variation
    
    # Enable adaptive window sizing for faster response
    t.set_adaptive_winlen(1)
    
    detections = []
    total_frames = 0
    
    while True:
        samples, read = s()
        is_beat = t(samples)
        
        # Record tempo at each beat
        if is_beat:
            current_time = total_frames / float(samplerate)
            bpm = t.get_bpm()
            confidence = t.get_confidence()
            detections.append((current_time, bpm, confidence))
        
        total_frames += read
        if read < hop_s:
            break
    
    return detections, samplerate

def analyze_accuracy(detections, ground_truth, samplerate):
    """
    Analyze detection accuracy against ground truth.
    
    Returns: dict with metrics
    """
    sections = ground_truth['sections']
    detected_sections = [False] * len(sections)
    section_errors = []
    response_times = []
    
    for i, section in enumerate(sections):
        start_time = section['start_time']
        end_time = section['end_time']
        expected_bpm = section['bpm']
        
        # Find detections in this section
        section_detections = [
            (t, bpm, conf) for t, bpm, conf in detections
            if start_time <= t < end_time
        ]
        
        if section_detections:
            # Use median BPM from section
            bpms = [bpm for _, bpm, _ in section_detections]
            detected_bpm = np.median(bpms)
            error = abs(detected_bpm - expected_bpm)
            
            # Detection is successful if error < 5 BPM
            if error < 5.0:
                detected_sections[i] = True
                section_errors.append(error)
                
                # Calculate response time (time to first detection in section)
                if i > 0:  # Skip first section
                    first_detection_time = section_detections[0][0]
                    response_time = first_detection_time - start_time
                    response_times.append(response_time)
    
    return {
        'detection_rate': sum(detected_sections) / len(sections) * 100,
        'avg_error': np.mean(section_errors) if section_errors else 0,
        'max_error': np.max(section_errors) if section_errors else 0,
        'avg_response': np.mean(response_times) if response_times else 0,
        'max_response': np.max(response_times) if response_times else 0,
    }

def print_comparison(original_metrics, optimized_metrics):
    """Print a comparison table of metrics."""
    print("\n" + "="*70)
    print("TEMPO TRACKING PERFORMANCE COMPARISON")
    print("="*70)
    print(f"{'Metric':<25} {'Original':<20} {'Optimized':<20} {'Change'}")
    print("-"*70)
    
    metrics = [
        ('Detection Rate (%)', 'detection_rate', '{:.1f}%'),
        ('Avg BPM Error', 'avg_error', '{:.2f} BPM'),
        ('Max BPM Error', 'max_error', '{:.2f} BPM'),
        ('Avg Response Time', 'avg_response', '{:.2f}s'),
        ('Max Response Time', 'max_response', '{:.2f}s'),
    ]
    
    for label, key, fmt in metrics:
        orig = original_metrics[key]
        opt = optimized_metrics[key]
        
        if key == 'detection_rate':
            change = ""
        elif opt < orig:
            pct_change = (orig - opt) / orig * 100 if orig > 0 else 0
            change = f"✓ -{pct_change:.1f}%"
        elif opt > orig:
            pct_change = (opt - orig) / orig * 100 if orig > 0 else 0
            change = f"✗ +{pct_change:.1f}%"
        else:
            change = "="
        
        print(f"{label:<25} {fmt.format(orig):<20} {fmt.format(opt):<20} {change}")
    
    print("="*70)

def main():
    """Main demonstration function."""
    # Check if test files exist
    test_dir = os.path.dirname(os.path.abspath(__file__))
    test_file = os.path.join(test_dir, '../../tests/test_bpm_changes.wav')
    ground_truth_file = os.path.join(test_dir, '../../tests/test_bpm_changes_ground_truth.json')
    
    if not os.path.exists(test_file):
        print(f"Error: Test file not found: {test_file}")
        print("Please run: python3 tests/generate_tempo_test_audio.py")
        return 1
    
    if not os.path.exists(ground_truth_file):
        print(f"Error: Ground truth file not found: {ground_truth_file}")
        print("Please run: python3 tests/generate_tempo_test_audio.py")
        return 1
    
    # Load ground truth
    ground_truth = load_ground_truth(ground_truth_file)
    
    print("Analyzing tempo tracking performance...")
    print(f"Test file: {os.path.basename(test_file)}")
    print(f"Sections: {len(ground_truth['sections'])}")
    print()
    
    # Run original mode
    print("Running original mode (default settings)...")
    start = time.time()
    original_detections, samplerate = detect_tempo_original(test_file)
    original_time = time.time() - start
    original_metrics = analyze_accuracy(original_detections, ground_truth, samplerate)
    print(f"  Completed in {original_time:.2f}s")
    print(f"  Detections: {len(original_detections)}")
    
    # Run optimized mode
    print("\nRunning optimized mode (with tempo priors + adaptive window)...")
    start = time.time()
    optimized_detections, _ = detect_tempo_optimized(test_file, expected_tempo=120)
    optimized_time = time.time() - start
    optimized_metrics = analyze_accuracy(optimized_detections, ground_truth, samplerate)
    print(f"  Completed in {optimized_time:.2f}s")
    print(f"  Detections: {len(optimized_detections)}")
    
    # Print comparison
    print_comparison(original_metrics, optimized_metrics)
    
    # Additional info
    print("\nNew Features Used in Optimized Mode:")
    print("  • set_tempo_prior_mean(120) - Centers detection around 120 BPM")
    print("  • set_tempo_prior_std(2.5)  - Allows ±2.5 BPM variation")
    print("  • set_adaptive_winlen(1)    - Enables adaptive window sizing")
    print()
    print("For genre-specific optimization, adjust tempo prior:")
    print("  # Electronic Dance Music (strict 128 BPM)")
    print("  t.set_tempo_prior_mean(128)")
    print("  t.set_tempo_prior_std(0.5)")
    print()
    print("  # Variable tempo classical music")
    print("  t.set_tempo_prior_mean(100)")
    print("  t.set_tempo_prior_std(3.0)")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
